version: "3.9"
services:
  notebook:
    container_name: glue_jupyter
    image: amazon/aws-glue-libs:glue_libs_1.0.0_image_01
    env_file: .env
    ports:
      - "8888:8888"
      - "4040:4040"
      - "10000:10000"
    entrypoint: /home/jupyter/jupyter_start.sh
    volumes:
      - ./aws-config:/root/.aws:rw
      - ./scripts:/home/jupyter/jupyter_default_dir
