name: Hub (Stg)
env:
  aws_deploy_account: ${{ secrets.AWS_ACCOUNT_HUB_STAGING}}
  aws_deploy_region: "eu-west-2"
  tf_apply: "true"
  tf_destroy: "false"
  environment: "Stg"
  terraform_state_s3_key_prefix: "platform-hub"
  build_path: "platform/network"
  automation_build_url: "https://github.com/LBHackney-IT/infrastructure/actions/workflows/platform_hub_stg.yml"
on:
  push:
    branches: [master, cd140-shared-infrastructure]
    paths:
      - "platform/network/**"
  pull_request:
    branches: [master, cd140-shared-infrastructure]
    paths:
      - "platform/network/**"
  workflow_dispatch:
jobs:
  build:
    name: AWS Terraform
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v2
      - name: Run AWS Terraform
        uses: ./.github/actions/aws-terraform-devops
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          tf_apply: ${{ env.tf_apply }}
          tf_destroy: ${{ env.tf_destroy }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_deploy_region: ${{ env.aws_deploy_region }}
          terraform_state_s3_key_prefix: ${{ env.terraform_state_s3_key_prefix }}
          build_path: ${{ env.build_path }}
          environment: ${{ env.environment }}
          automation_build_url: ${{ env.automation_build_url }}
          aws_deploy_account: ${{ env.aws_deploy_account }}
          aws_deploy_iam_role_name: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          branch: ${GITHUB_REF##*/}
