"""Subs list for address cleaning"""

full_address_regex_clean = [[",\s*", ""],
                            ["\(", " "],
                            ["\)", " "],
                            [" +", " "],
                            [" ?- ?$", ""]]

full_address_regex_streets = [[" st$", " street"],
                              [" rd ", " road "],
                              [" rd$", " road"],
                              [" ave ", " avenue "],
                              [" ave$", " avenue"],
                              [" ct ", " court "],
                              [" ct$", " court"]]

full_address_regex_subs = [["hse excl bst", " "],
                           ["hse exc bst", " "],
                           ["hse excl", "house excluding"],
                           [" hse ", " house "],
                           [" hse$", " house"],
                           [" est ", " estate "],
                           [" bst ", " basement "],
                           ["^bst ", "basement "],
                           [" bst$", " basement"],
                           [" lgnd ", " lower ground "],
                           ["^lgnd ", "lower ground "],
                           [" lgnd$", " lower ground"],
                           [" gnd ", " ground "],
                           ["^gnd ", "ground "],
                           [" gnd$", " ground"],
                           [" 1st ", " first "],
                           ["^1st ", "first "],
                           [" 1st$", " first"],
                           [" 2nd ", " second "],
                           ["^2nd ", "second "],
                           [" 2nd$", " second"],
                           [" 3rd ", " third "],
                           ["^3rd ", "third "],
                           [" 3rd$", " third"],
                           [" 4th ", " fourth "],
                           ["^4th ", "fourth "],
                           [" 4th$", " fourth"],
                           [" 5th ", " fifth "],
                           ["^5th ", "fifth "],
                           [" 6th ", " sixth "],
                           ["^6th ", "sixth "],
                           [" 6th$", " sixth"],
                           [" 7th ", " seventh "],
                           ["^7th ", "seventh "],
                           [" 7th$", " seventh"],
                           [" & ", " and "],
                           [" &", " and"],
                           [" at ", " "],
                           [" of ", " "],
                           [" r/o ", " rear of "],
                           ["^r/o ", "rear of "],
                           [" r/o$", " rear of"],
                           [" k/a ", " known as "],
                           ["^k/a ", "known as "],
                           [" k/a$", " known as"],
                           [" ft ", " front "],
                           ["^ft ", "front "],
                           [" ft$", " front"],
                           [" rr ", " rear "],
                           ["^rr ", "rear "],
                           [" rr$", " rear"],
                           [" lhs ", " left "],
                           ["^lhs ", "left "],
                           [" lhs$", " left"],
                           [" rhs ", " right "],
                           ["^rhs ", "right "],
                           [" rhs$", " right"],
                           [" pt ", " part "],
                           ["^pt ", "part "],
                           [" pt$", " part"],
                           [" flr ", " floor "],
                           [" flr$", " floor"],
                           [" flrs ", " floor "],
                           [" flrs$", " floor"],
                           [" mais ", " flat "],
                           ["^mais ", "flat "],
                           [" mais$", " flat"],
                           [" rm ", " room "],
                           ["^rm ", "room "],
                           [" rm$", " room"],
                           [" rms ", " room "],
                           ["^rms ", "room "],
                           [" rms$", " room"],
                           [" mezz ", " mezzanine "],
                           ["^mezz ", "mezzanine "],
                           [" mezz$", " mezzanine"]]

clean_trim_address_regex_subs = [[" and ", " "],
                                 [" floor ", " "],
                                 [" floor$", " "],
                                 [" flat ", " "],
                                 ["^flat ", " "],
                                 [" flat$", " "],
                                 [" room ", " "],
                                 ["^room ", " "],
                                 [" room$", " "]]
