#!/bin/bash

set -e

# They probably are but check if terraform and git are installed otherwise skip pre-commit hook
if ! command -v terraform &> /dev/null
then
  echo "Terraform not installed"
  exit 0;
fi

if ! command -v git &> /dev/null
then
  echo "Git not installed"
  exit 0;
fi

if ! command -v pip &> /dev/null
then
  echo "pip not installed"
  exit 0;
else
  if ! command -v ggshield &> /dev/null
  then
    pip install pre-commit &> /dev/null
    pip install -U ggshield &> /dev/null
    ggshield auth login &> /dev/null
  fi
fi

#Find all the directories with terraform files in them
terraform_directories=$(find "$(pwd)" -type f -name '*.tfvars' -or -name '*.tf' | sed -r 's|/[^/]+$||' | sort | uniq )

#Format the files in the terraform directories and add
for directory in $terraform_directories; do
  if [[ "$directory" != *".terraform"* ]]; then
    for formatted_file in $(terraform fmt "$directory"); do
      git add "$(pwd)"/"$formatted_file"
    done
  fi
done

ggshield scan pre-commit
