name: AWS Terraform
description: Runs Terraform against Hackney AWS
inputs:
  aws_access_key_id:
    description: "AWS access key to use"
    required: true
  aws_secret_access_key:
    description: "AWS secret access key to use"
    required: true
  aws_deploy_region:
    description: "AWS region to deploy to"
    default: "eu-west-2"
    required: true
  terraform_state_s3_key_prefix:
    description: "S3 key prefix for Terraform state"
    required: true
  build_path:
    description: "Build path that contains the source"
    required: true
  environment:
    description: "Name of the environment e.g. dev, stg, prod, mgmt"
    required: true
  google_project_id:
    description: "Id of google project to which service accounts will be deployed to"
    required: true
  automation_build_url:
    description: "URL of the GitHub Action Run to pass to Terraform"
    required: true
  aws_deploy_account_id:
    description: "AWS account id to deploy to"
    required: true
  aws_api_account_id:
    description: "AWS api account id to deploy to"
    required: true
  aws_mosaic_prod_account_id:
    description: "AWS Mosaic prod account id to connect to"
    required: true
  aws_data_platform_account_id:
    description: "AWS Data Platform account ID"
    required: true
  aws_api_vpc_id:
    description: "AWS API Account VPC ID"
    required: true
  aws_housing_vpc_id:
    description: "AWS Housing Account VPC ID"
    required: true
  aws_mosaic_vpc_id:
    description: "AWS Mosaic Account VPC ID"
    required: true
  aws_dp_vpc_id:
    description: "Data Platform VPC ID"
    required: true
  aws_hackit_account_id:
    description: "AWS HackIT account id to deploy to"
    required: true
  aws_deploy_iam_role_name:
    description: "AWS IAM role name to assume for deployment"
    required: true
  copy_liberator_to_pre_prod_lambda_execution_role:
    description: "AWS IAM role name to assume for triggering the lambda to copy liberator data to pre-prod"
    required: true
  sync_production_to_pre_production_task_role:
    description: "Role arn for the prod to pre-prod raw, refined & trusted zones sync task. Only used in pre-production environment."
    required: true
  pre_production_liberator_data_storage_kms_key_arn:
    description: "KMS Key ARN for the liberator data storage bucket in pre production"
    required: true
  branch:
    description: "Git branch being ran against"
    required: true
  terraform_import:
    description: "Terraform import statement"
    default: ""
    required: true
  terraform_destroy:
    description: 'Runs a Terraform destroy if the value is set to "destroy_me". Else does nothing'
    default: ""
    required: false
  terraform_remove:
    description: "Terraform state rm statement"
    default: ""
    required: false

runs:
  using: "composite"
  steps:
    - name: Setup build environment
      id: setup
      run: |
        ${{ github.action_path }}/../.helpers/box.sh "Setting up build environment"
      shell: bash
      working-directory: "${{ inputs.build_path }}"

    - name: Terraform Init
      id: init
      run: |
        ${{ github.action_path }}/../.helpers/box.sh "Running Terraform init"
        echo -e "Configuring AWS credentials."
        aws configure set default.region eu-west-2 > /dev/null 2>&1
        aws configure set aws_access_key_id ${{ inputs.aws_access_key_id }} > /dev/null 2>&1
        aws configure set aws_secret_access_key ${{ inputs.aws_secret_access_key }} > /dev/null 2>&1
        terraform init -backend-config="region=eu-west-2" -backend-config="dynamodb_table=lbhackney-terraform-state-lock" -backend-config="encrypt=true" -backend-config="workspace_key_prefix=${{ inputs.terraform_state_s3_key_prefix }}" -backend-config="bucket=lbhackney-terraform-state" -backend-config="key=${{ inputs.terraform_state_s3_key_prefix }}/${{ inputs.environment }}-terraform.tfstate"
        echo -e "Terraform S3 bucket: lbhackney-terraform-state"
        echo -e "Terraform state file: ${{ inputs.terraform_state_s3_key_prefix }}/${{ inputs.environment }}-terraform.state"
        echo -e "\n"
      shell: bash
      working-directory: "${{ inputs.build_path }}"

    - name: Terraform Import
      id: import
      run: |
        if [ "${{ inputs.terraform_import }}" != "" ]; then
            ${{ github.action_path }}/../.helpers/box.sh "Running Terraform import"
            if [ "${{ inputs.branch }}" == "main" ]; then
              terraform import -var-file='../config/${{ inputs.environment }}.tfvars' -var 'aws_deploy_region=${{ inputs.aws_deploy_region }}' -var 'aws_deploy_account_id=${{ inputs.aws_deploy_account_id }}' -var 'aws_api_account_id=${{ inputs.aws_api_account_id }}' -var 'aws_mosaic_prod_account_id=${{ inputs.aws_mosaic_prod_account_id }}' -var 'aws_data_platform_account_id=${{ inputs.aws_data_platform_account_id }}' -var 'aws_hackit_account_id=${{ inputs.aws_hackit_account_id }}' -var 'aws_deploy_iam_role_name=${{ inputs.aws_deploy_iam_role_name }}' -var 'environment=${{ inputs.environment }}' -var 'google_project_id=${{ inputs.google_project_id }}' -var 'automation_build_url=${{ inputs.automation_build_url }}' ${{ inputs.terraform_import }}
            else
              echo -e "Not on default branch branch, so skipping Terraform import."
            fi
        fi
      shell: bash
      working-directory: "${{ inputs.build_path }}"

    - name: Terraform Remove
      id: remove
      run: |
        if [ "${{ inputs.terraform_remove }}" != "" ]; then
            ${{ github.action_path }}/../.helpers/box.sh "Running Terraform remove"
            if [ "${{ inputs.branch }}" == "main" ]; then
              terraform state rm ${{ inputs.terraform_remove }}
            else
              echo -e "Not on default branch branch, so skipping Terraform remove."
            fi
        fi
      shell: bash
      working-directory: "${{ inputs.build_path }}"

    - name: Terraform Destroy
      id: destroy
      run: |
        if [ "${{ inputs.terraform_destroy }}" == "destroy_me" ]; then
            ${{ github.action_path }}/../.helpers/box.sh "Running Terraform destroy"
            if [ "${{ inputs.branch }}" == "main" ]; then
              terraform destroy -var-file='../config/${{ inputs.environment }}.tfvars' -var 'aws_deploy_region=${{ inputs.aws_deploy_region }}' -var 'aws_deploy_account_id=${{ inputs.aws_deploy_account_id }}' -var 'aws_api_account_id=${{ inputs.aws_api_account_id }}' -var 'aws_mosaic_prod_account_id=${{ inputs.aws_mosaic_prod_account_id }}' -var 'aws_data_platform_account_id=${{ inputs.aws_data_platform_account_id }}' -var 'aws_hackit_account_id=${{ inputs.aws_hackit_account_id }}' -var 'aws_deploy_iam_role_name=${{ inputs.aws_deploy_iam_role_name }}' -var 'environment=${{ inputs.environment }}' -var 'google_project_id=${{ inputs.google_project_id }}' -var 'automation_build_url=${{ inputs.automation_build_url }}' -var 'aws_api_vpc_id=${{ inputs.aws_api_vpc_id }}' -var 'aws_housing_vpc_id=${{ inputs.aws_housing_vpc_id }}' -var 'aws_mosaic_vpc_id=${{ inputs.aws_mosaic_vpc_id }}' -var 'aws_dp_vpc_id=${{ inputs.aws_dp_vpc_id }}' -var 'copy_liberator_to_pre_prod_lambda_execution_role=${{ inputs.copy_liberator_to_pre_prod_lambda_execution_role }}' -var 'sync_production_to_pre_production_task_role=${{ inputs.sync_production_to_pre_production_task_role }}' -var 'pre_production_liberator_data_storage_kms_key_arn=${{ inputs.pre_production_liberator_data_storage_kms_key_arn }}' -auto-approve
              ${{ github.action_path }}/../.helpers/success_destroy.sh
              echo -e "Terraform run completed successfully."
            else
              echo -e "Not on default branch branch, so skipping Terraform destroy."
            fi
        fi
      shell: bash
      working-directory: "${{ inputs.build_path }}"

    - name: Terraform Plan
      id: plan
      run: |
        if [ "${{ inputs.terraform_destroy }}" != "destroy_me" ]; then
          ${{ github.action_path }}/../.helpers/box.sh "Running Terraform plan"
          terraform plan -var-file='../config/${{ inputs.environment }}.tfvars' -var 'aws_deploy_region=${{ inputs.aws_deploy_region }}' -var 'aws_deploy_account_id=${{ inputs.aws_deploy_account_id }}' -var 'aws_api_account_id=${{ inputs.aws_api_account_id }}' -var 'aws_mosaic_prod_account_id=${{ inputs.aws_mosaic_prod_account_id }}' -var 'aws_data_platform_account_id=${{ inputs.aws_data_platform_account_id }}' -var 'aws_hackit_account_id=${{ inputs.aws_hackit_account_id }}' -var 'aws_deploy_iam_role_name=${{ inputs.aws_deploy_iam_role_name }}' -var 'environment=${{ inputs.environment }}' -var 'google_project_id=${{ inputs.google_project_id }}' -var 'automation_build_url=${{ inputs.automation_build_url }}' -var 'aws_api_vpc_id=${{ inputs.aws_api_vpc_id }}' -var 'aws_housing_vpc_id=${{ inputs.aws_housing_vpc_id }}' -var 'aws_mosaic_vpc_id=${{ inputs.aws_mosaic_vpc_id }}' -var 'aws_dp_vpc_id=${{ inputs.aws_dp_vpc_id }}' -var 'copy_liberator_to_pre_prod_lambda_execution_role=${{ inputs.copy_liberator_to_pre_prod_lambda_execution_role }}' -var 'sync_production_to_pre_production_task_role=${{ inputs.sync_production_to_pre_production_task_role }}' -var 'pre_production_liberator_data_storage_kms_key_arn=${{ inputs.pre_production_liberator_data_storage_kms_key_arn }}' -input=false -out=plan.out
          echo -e "\n"
        fi
      shell: bash
      working-directory: "${{ inputs.build_path }}"

#    - name: Terraform Compliance
#      shell: bash
#      working-directory: "${{ inputs.build_path }}"
#      run: |
#        sudo apt-get update
#        sudo apt-get install pip
#        pip install --upgrade orjson
#        pip install terraform-compliance[faster_parsing]
#        terraform-compliance -f ../compliance/ -p plan.out

    - name: Terraform Apply
      id: apply
      run: |
        if [ "${{ inputs.terraform_destroy }}" != "destroy_me" ] && [ "${{ inputs.terraform_remove }}" == "" ]; then
          if [ "${{ inputs.branch }}" == "main" ]; then
            ${{ github.action_path }}/../.helpers/box.sh "Running Terraform apply"
            terraform apply -auto-approve -input=false plan.out
          else
            echo -e "Not on main branch, so skipping Terraform apply."
          fi
          ${{ github.action_path }}/../.helpers/success.sh
          echo -e "Terraform run completed successfully."
        fi
      shell: bash
      working-directory: "${{ inputs.build_path }}"
