version: "3.9"
services:
  unit_tests:
    container_name: unit_test_runner
    image: amazon/aws-glue-libs:glue_libs_1.0.0_image_01
    working_dir: /root/scripts
    ports:
      - "4041:4040"
    entrypoint: bash -c "pip install -r ./requirements.test.txt && /home/aws-glue-libs/bin/gluepytest ./${filename}"
    volumes:
      - .:/root/scripts