name: 'CI'
on:
  push:
    branches-ignore:
      - "main"
    paths:
      - 'scripts/**'
      - 'lambdas/**'
  workflow_call:
    secrets:
      SONAR_TOKEN:
        required: true
      GITHUB_TOKEN:
        required: true

jobs:
  CI:
    uses: ./.github/workflows/test-python-and-lambda.yml
    secrets:
      SONAR_TOKEN : ${{ secrets.SONAR_TOKEN }}
      GITHUB_TOKEN : ${{ secrets.GITHUB_TOKEN }}
