name: 'CI'
on:
  push:
    branches-ignore:
      - "main"
    paths:
      - 'scripts/**'
      - 'lambdas/**'
      - 'modules/kafka-event-streaming/scripts/**'

jobs:
  CI:
    uses: ./.github/workflows/test-python-and-lambda.yml
