name: Data-Platform (Staging)
concurrency: staging-deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      terraform_import:
        description: "Terraform import statements"
        required: false
      terraform_remove:
        description: "Terraform state rm statements"
        required: false

jobs:
  pre-deploy-checks:
    uses:  LBHackney-IT/Data-Platform/.github/workflows/ci.yml@main
  build-and-deploy:
    needs: ["pre-deploy-checks"]
    uses: LBHackney-IT/Data-Platform/.github/workflows/deploy_terraform.yml@main
    with:
      terraform_import: ${{ github.event.inputs.terraform_import }}
      terraform_remove: ${{ github.event.inputs.terraform_remove }}
      environment: "stg"
      automation_build_url: "https://github.com/LBHackney-IT/data-platform/actions/workflows/data_platform_stg.yml"
    secrets:
      google_project_id: ${{ secrets.GOOGLE_PROJECT_ID_STG }}
      aws_deploy_account: ${{ secrets.AWS_ACCOUNT_DATA_PLATFORM_STG }}
