name: Data-Platform (Production)
env:
  aws_deploy_account: ${{ secrets.AWS_ACCOUNT_DATA_PLATFORM_PROD }}
  aws_api_account: ${{ secrets.AWS_API_ACCOUNT_PROD }}
  aws_deploy_region: "eu-west-2"
  google_project_id: ${{ secrets.GOOGLE_PROJECT_ID_PROD }}
  environment: "prod"
  automation_build_url: "https://github.com/LBHackney-IT/data-platform/actions/workflows/data_platform_prod.yml"

  network_state_prefix: "data-platform-network"
  network_build_path: "./terraform-networking"

  main_state_prefix: "data-platform"
  main_build_path: "./terraform"

on:
  release:
    types: [published]
    paths-ignore:
      - "infrastructure/projects/**"
      - "infrastructure/platform/**"
  workflow_dispatch:
    inputs:
      terraform_import:
        description: "Terraform import statements"
        required: false
      terraform_remove:
        description: "Terraform state rm statements"
        required: false

jobs:
  build:
    name: AWS Terraform
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v2
      - name: Setup Node.js 14
        uses: actions/setup-node@v2
        with:
          node-version: "14"
      - name: Install dependencies in rds-database-snapshot-replicator lambda
        working-directory: "./lambdas/rds-database-snapshot-replicator"
        run: npm install
      - name: Install dependencies in liberator_sftp_to_s3 lambda
        working-directory: "./lambdas/liberator_sftp_to_s3"
        run: npm install
      - name: Set up Google Cloud Credentials
        run: |
          echo $GOOGLE_CREDENTIALS >> ./google_service_account_creds.json
        shell: bash
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS_PROD }}
      - name: Deploy Data Platform Network
        uses: ./.github/actions/aws-terraform
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_deploy_region: ${{ env.aws_deploy_region }}
          terraform_state_s3_key_prefix: ${{ env.network_state_prefix }}
          build_path: ${{ env.network_build_path }}
          automation_build_url: ${{ env.automation_build_url }}
          environment: ${{ env.environment }}
          google_project_id: ${{ env.google_project_id }}
          aws_deploy_account: ${{ env.aws_deploy_account }}
          aws_api_account: ${{ env.aws_api_account }}
          aws_deploy_iam_role_name: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          branch: ${GITHUB_REF##*/}
          terraform_import: ${{ github.event.inputs.terraform_import }}
          terraform_remove: ${{ github.event.inputs.terraform_remove }}
          # DANGER ZONE
          # In order to allow you to run a Terraform destroy (that will delete all AWS resources managed by Terraform,
          # you can set terraform_destroy: 'destroy_me'. Not providing a value or any other value except 'destroy_me' will
          # cause nothing to happen. The example here, with the value set to false is to ensure you've read this comment ;)
          terraform_destroy: false
      - name: Assign Network Properties
        working-directory: "./terraform-networking"
        run: |
          VPC_ID=$(terraform output vpc_id)
          echo "aws_vpc_id=$VPC_ID" >> ../config/terraform/prod.tfvars
      - name: Deploy Data Platform Infastructure
        uses: ./.github/actions/aws-terraform
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_deploy_region: ${{ env.aws_deploy_region }}
          terraform_state_s3_key_prefix: ${{ env.main_state_prefix }}
          build_path: ${{ env.main_build_path }}
          automation_build_url: ${{ env.automation_build_url }}
          environment: ${{ env.environment }}
          google_project_id: ${{ env.google_project_id }}
          aws_deploy_account: ${{ env.aws_deploy_account }}
          aws_api_account: ${{ env.aws_api_account }}
          aws_deploy_iam_role_name: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          branch: "main"
          terraform_import: ${{ github.event.inputs.terraform_import }}
          terraform_remove: ${{ github.event.inputs.terraform_remove }}
          # DANGER ZONE
          # In order to allow you to run a Terraform destroy (that will delete all AWS resources managed by Terraform,
          # you can set terraform_destroy: 'destroy_me'. Not providing a value or any other value except 'destroy_me' will
          # cause nothing to happen. The example here, with the value set to false is to ensure you've read this comment ;)
          terraform_destroy: false
      - name: Build and delpoy image to ECR
        working-directory: "./terraform"
        run: |
          ROLE_ARN=arn:aws:iam::${{ env.aws_deploy_account }}:role/${{ secrets.AWS_ROLE_TO_ASSUME }} ../docker/sql-to-parquet/deploy.sh
