name: Data-Platform (Staging)
concurrency: staging-deploy
env:
  aws_deploy_account: ${{ secrets.AWS_ACCOUNT_DATA_PLATFORM_STG }}
  google_project_id: ${{ secrets.GOOGLE_PROJECT_ID_STG }}
  environment: "stg"
  automation_build_url: "https://github.com/LBHackney-IT/data-platform/actions/workflows/data_platform_stg.yml"

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      terraform_import:
        description: "Terraform import statements"
        required: false
      terraform_remove:
        description: "Terraform state rm statements"
        required: false

jobs:
  pre-deploy-checks:
    uses:  LBHackney-IT/Data-Platform/.github/workflows/ci.yml@run-tflint-on-branches
  build-and-deploy:
    needs: ["pre-deploy-checks"]
    uses: LBHackney-IT/Data-Platform/.github/workflows/deploy_terraform.yml@run-tflint-on-branches
    with:
      terraform_import: ${{ github.event.inputs.terraform_import }}
      terraform_remove: ${{ github.event.inputs.terraform_remove }}
      environment: ${{ env.environment }}
      automation_build_url: ${{ env.automation_build_url }}
    secrets:
      google_project_id: ${{ env.google_project_id }}
      aws_deploy_account: ${{ env.aws_deploy_account }}
