name: Lint Python Files - Flake8
# flake8 to check the syntax of changed files but ingore E501 error (line too long)

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2
      with:
        fetch-depth: 0  # Ensure the entire history is fetched

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    
    - name: Install Flake8
      run: pip install flake8
      
    - name: Get Changed Files
      id: changed-files
      uses: tj-actions/changed-files@v44
      with:
        files: |
          **.py

    - name: Lint Changed Python Files
      if: steps.changed-files.outputs.any_changed == 'true'
      run: |
        CHANGED_FILES="${{ steps.changed-files.outputs.all_changed_files }}"
        IFS=' ' read -r -a FILE_ARRAY <<< "$CHANGED_FILES"
        IGNORED_PATHS=("scripts/jobs/parking/")
        for FILE in "${FILE_ARRAY[@]}"
        do
          skip_file=false
          for IGNORED_PATH in "${IGNORED_PATHS[@]}"
          do
            if [[ $FILE == *"$IGNORED_PATH"* ]]; then
              skip_file=true
              break
            fi
          done
          if [ "$skip_file" = false ]; then
            flake8 $FILE --ignore=E501
          fi
        done

