name: CI

on:
  pull_request:
    branches:
      - main
    paths:
      - "terraform-networking/**"
      - "terraform-backend-setup/**"
      - "terraform/**"

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Terraform
        uses: hashicorp/setup-terraform@v1.2.1
        with:
          terraform_version: 0.14.9
      - name: Set up dummy Google Cloud Credentials
        run: |
          echo "{}" >> ./google_service_account_creds.json
        shell: bash
      - name: Download dependencies
        working-directory: "./dependencies"
        run: make all
      - name: Run `terraform validate` on Terraform Networking
        working-directory: "./terraform-networking"
        run: |
          terraform init -backend=false
          terraform validate
      - name: Run `terraform validate` on Backend Setup
        working-directory: "./terraform-backend-setup"
        run: |
          terraform init -backend=false
          terraform validate
      - name: Run `terraform validate` on Terraform
        working-directory: "./terraform"
        run: |
          terraform init -backend=false
          terraform validate
