name: Example Project (DevScratch)
env:
  aws_deploy_account: ${{ secrets.AWS_ACCOUNT_DEVSCRATCH}}
  aws_deploy_region: "eu-west-2"
  environment: "Dev"
  terraform_state_s3_key_prefix: "project-example"
  build_path: "projects/example"
  automation_build_url: "https://github.com/LBHackney-IT/infrastructure/actions/workflows/project_example.yml"
on:
  push:
    branches: [master]
    paths:
      - "projects/example/**"
  pull_request:
    branches: [master]
    paths:
      - "projects/example/**"
  workflow_dispatch:
jobs:
  build:
    name: AWS Terraform
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v2
      - name: Run AWS Terraform
        uses: ./.github/actions/aws-terraform
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_deploy_region: ${{ env.aws_deploy_region }}
          terraform_state_s3_key_prefix: ${{ env.terraform_state_s3_key_prefix }}
          build_path: ${{ env.build_path }}
          environment: ${{ env.environment }}
          automation_build_url: ${{ env.automation_build_url }}
          aws_deploy_account: ${{ env.aws_deploy_account }}
          aws_deploy_iam_role_name: ${{ secrets.AWS_ROLE_TO_ASSUME }} 
