name: Python Unit Tests

on: push

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run `make test`
        run: |
          cd scripts
          make test
