name: Test and Validate

on:
  workflow_call:

jobs:
  tests:
    name: Test Python Jobs & Lambda Functions
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Test Python Jobs
        run: |
          cd scripts
          make test
      - name: Test Lambda Functions
        run: |
          cd lambdas
          make test