name: Test and Validate

on:
  workflow_call:

jobs:
  tests:
    name: Test Python Jobs & Lambda Functions
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test Python Jobs
        run: |
          cd scripts
          make test
      - name: Test Lambda Functions
        run: |
          cd lambdas
          make test

  sonar:
    name: Sonar Scan in ${{ inputs.build_path }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Sonar Cloud Scan in ./lambdas
        uses: ./.github/actions/sonar-cloud-scan
        with:
          sonar_token: ${{ secrets.SONAR_TOKEN }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
